spring:
  application:
    name: mms
server:
  port: 9211
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=member
#    username:
#    password:
mms:
  welcomeStr: "Welcome to MMS UAT"
